app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from members.views import signup_view
from posts.views import post_list

urlpatterns_apis = [
    path('members/', include('members.urls.apis')),
    path('posts/', include('posts.urls.apis')),
]

urlpatterns = [
    path('api/', include(urlpatterns_apis)),

    path('', signup_view, name='signup'),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls.views')),
    path('posts/', include('posts.urls.views')),

    path('explore/tags/<str:tag>/', post_list, name='post-list-by-tag'),
]

urlpatterns += static(
    # prefix='/media/',
    # URL 앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root위체어서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/posts/urls.py
from django.urls import path

from . import views
from .views import post_create, comment_create

app_name = 'posts'

urlpatterns = [
    # /posts/
    path('', views.post_list, name='post-list'),
    # path('explore/tags/<str:tag>/', post_list_by_tag, name='post-list-by-tag'),

    # /posts/3/like/
    path('<int:pk>/like/', views.post_like, name='post-like'),

    path('create/', post_create, name="post-create"),
    path('<int:post_pk>/comments/create/', comment_create, name="comment-create"),
]

app/posts/models.py
import re

from django.db import models
from members.models import User


class Post(models.Model):
    TAG_PATTERN = re.compile(r'#(\w+)')
    # 인스타그램의 포스트
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    content_html = models.TextField(blank=True)
    like_users = models.ManyToManyField(User, through='PostLike', related_name='like_posts_set',)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(
        'Tag', verbose_name='해시태그 목록', related_name="posts", blank=True,
    )


    def __str__(self):
        return f'author: {self.author}, content: {self.content}, like_users: {self.like_users}, created:{self.created}'


    def _save_html(self):
        """
        content 속성의 값을 사용해서 해시태그에 해당하는 문자열을 a태그로 바꾸어 줌
        :return: 해시태그가 a태그로 변환된 HTML
        """
        # 자신의 content_html에 #Python -> <a ~>로 변환된 문자열을 저장
        self.content_html = re.sub(
            self.TAG_PATTERN,
            r'<a href="/explore/tags/\g<1>">#\g<1></a>',
            self.content,
        )

    def _save_tags(self):
        """
        content에 포함된 해시태그 문자열 (ex. #Python)의 Tag를 만들고,
        자신의 tags Many-to-many field에 추가한다.
        :return:
        """
        # Post 객체가 저장될 때, content 값을 분석해서
        # 자신의 tags항목을 적절히 채워줌
        # ex) #Django #Python이 온 경우
        # post.tags.all() 시
        # name이 Django, Python인 Tag 2개 QuerySet이 리턴되어야 함

        # instance, created = Tag.objects.get_or_create(속성)
        # ManyToManyField.set

        tag_name_list = re.findall(self.TAG_PATTERN, self.content)

        # self.tags.clear()

        # for tag_name in tag_name_list:
        #     tag = Tag.objects.get_or_create(name=tag_name)[0]
        #     self.tags.add(tag)

        tags = [Tag.objects.get_or_create(name=tag_name)[0] for tag_name in tag_name_list]
        self.tags.set(tags)

        # self.content = content_html
        # print("알고싶은 정보2", self.content)
        # self.save()

    def save(self, *args, **kwargs):
        self._save_html()
        super().save(*args, **kwargs)
        self._save_tags()

class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/image')


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()


class PostLike(models.Model):
    """
    사용자가 좋아요 누른 Post 정보를 저장
    Many-to-many 필드를 중간모델을 거쳐 사용
    언제 생성되었는지 Extra field로 저장
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    """
    Many-to-many에서 필드는 Post에 클래스에 작성
    HashTag의 Tag를 담당
    Post입장에서 post.tags.all()로 연결된 전체 Tag를 불러올 수 있어야 함
    Tag 입장에서 tag.posts.all()로 연결된 전체 Post를 불러올 수 있어야 함

    Django admin에서 결과를 볼 수 있도록 admin.py에 적절히 내용 기록
    중계모델(Intermediate model)을 사용할 필요 없음
    """
    name = models.CharField('', max_length=100)

    def __str__(self):
        return self.name

app/posts/forms.py
from django import forms
from django.db import models


class PostCreateForm(forms.Form):
    """
    이 Form에 들어갈 입력 요소
        Image(File)
        Text
    """
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class':'form-control',
                'multiple': True,
        })
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )

    def save(self):
        pass


class CommentCreateForm(forms.Form):
    content = forms.CharField(
        max_length=10,
        widget=forms.Textarea()
    )

    def save(self, post, author):
        return post.postcomment_set.create(
            author=author,
            content=self.cleaned_data['content']
        )

app/members/urls/views.py
from django.urls import path

from .. import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('naver-login/', views.naver_login, name='naver-login'),
]

app/posts/urls/views.py
from django.urls import path

from .. import views

app_name = 'posts'

urlpatterns = [
    # /posts/
    path('', views.post_list, name='post-list'),
    # path('explore/tags/<str:tag>/', post_list_by_tag, name='post-list-by-tag'),

    # /posts/3/like/
    path('<int:pk>/like/', views.post_like, name='post-like'),

    path('create/', views.post_create, name="post-create"),
    path('<int:post_pk>/comment/', views.comment_list),
    path('<int:post_pk>/comments/create/', views.comment_create, name="comment-create"),

]

app/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from posts.forms import PostCreateForm, CommentCreateForm
from posts.models import Post, PostLike, PostImage, PostComment


def post_list(request, tag=None):
    """
    1. 로그인 완료 후 이 페이지로 이동하도록 함
    2. index에 접근할 때 로그인이 되어있다면, 이 페이지로 이동하도록 함
        로그인 되어있는지 확인:
            User.is_authenticated가 True인지 체크

    URL :       /post/ (posts.urls를 사용, config.urls에서 include)
    Template : templates/posts/post-list.html
                <h1>Post List</h1>

    'posts'라는 키로 모든 Post QuerySet을 전달
    순서는 pk의 역순
    그리고 전달받은 QuerySet을 순회하며 적절히 Post내용을 출력
    """
    if tag is None:
        posts = Post.objects.order_by('-pk')
    else:
        posts = Post.objects.filter(tags__name__iexact=tag).order_by('-pk')

    comment_form = CommentCreateForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/post-list.html', context)


def post_like(request, pk):
    """
    pk가 pk인 Post와 (변수명 post사용)
    request.user로 전달되는 User(변수명 user사용)에 대해

    1. PostLike(post=post, user=user)인 객체가 존재하는지 확인
        없다면 생성한다.
        이미 있다면, 삭제한다.
    2. 완료 후 posts:post-list로 redirect한다.

    URL : /posts/<pk>/like/
    """

    post = Post.objects.get(pk=pk)
    user = request.user
    print('post')
    print('user')

    post_like_qs = PostLike.objects.filter(post=post, user=user)

    if post_like_qs.exists():
        post_like_qs.delete()

    else:
        PostLike.objects.create(post=post, user=user)

    return redirect('posts:post-list')


def post_create(request):
    """
    URL: /posts/create/
    Template: /posts/post-create.html

    forms.PostCreateForm을 사용

    """
    if request.method == 'POST':
        """
        새 Post 생성
        user는 request.user
        전달받는 데이터 : image, text
            image는 request.FILES에 있음
            text는 request.POST에 있음
        Post를 생성
            request.user와 text를 사용
        PostImage를 생성
            post와 전달받은 image를 사용
        모든 생성이 완료되면 posts:post-list로 redirect
        """
        text = request.POST['text']
        images = request.FILES.getlist('image')

        post = Post.objects.create(
            author=request.user,
            content=text,
        )

        for image in images:
            post.postimage_set.create(image=image)

        return redirect('posts:post-list')
    else:
        form = PostCreateForm()
        context = {
            'form': form,
        }
        return render(request, 'posts/post-create.html', context)


def comment_create(request, post_pk):
    # URL: /posts/<int:post_pk>/comments/create/
    # Template: 없음 (post_list.html 내에 Form을 구현)
    #  post-list.html 내부에서, 각 Post마다 자신에게 연결된 PostComment목록을 보여주도록 함
    #   보여주는 형식은
    #   <ul>
    #       <li><b>작성자명</b><span>내용</span>/li>
    #       <li><b>작성자명</b><span>내용</span>/li>
    #   </ul>
    # Form: post.forms.CommentCreateForm

    content = request.POST['content']

    post = Post.objects.get(pk=post_pk)

    # Form 인스턴스를 만드는데, data에 request.POST로 전달된 dict 입력
    form = CommentCreateForm(data=request.POST)

    # Form 인스턴스 생성 시, 주어진 데이터가 해당 Form이 가진 Field들에 적절한 데이터인지 검증
    if form.is_valid():
        # comment = form.cleaned_data['comment']
        form.save(post=post, author=request.user)

        PostComment.objects.create(post=post, author=request.user, content=content)
        # post.postcomment_set.creat(post=post, author=request.user, content=comment)

    return redirect('posts:post-list')

def comment_list(request, post_pk):
    # URL:  /posts/1/comments/
    # Template: /posts/comment-list.html

    # post_pk가 pk인 Post에 연결된 모든 PostComment 목록을 보여주기
    # Template에서는 PostCommnet의 pk, content, author 항목을 보여준다.

    post = Post.objects.get(pk=post_pk)
    comments = post.postcomment_set.all()

    context = {
        'comments': comments,
    }

    return render(request, 'posts/comment-list.html', context)

app/templates/posts/comment-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% for comment in comments %}
    <div>{{comment.pk}}</div>
    <div>{{comment.content}}</div>
    <div>{{comment.author}}</div>
{% endfor %}
</body>
</html>

app/templates/posts/post-create.html
<html>
<body>
    <form action="{% url 'posts:post-create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">작성</button>
    </form>
</body>
</html>

app/templates/posts/post-list.html
{% extends 'base.html' %}

{% block content %}
<div>
    {% if request.user.is_authenticated %}
    <a href="{%url 'members:logout' %}" class="btn btn-primary btn-md mt-3"> 로그아웃 버튼</a>
    <a href="{%url 'posts:post-create' %}" class="btn btn-primary btn-md mt-3"> 글작성 버튼</a>
    {% endif %}
</div>

<div>{{request.user}}</div>
<div>{{request.user.is_authenticated}}</div>

{% for post in posts %}
<div>작성자: {{post.author}}</div>
<div>작성일시: {{post.created}}</div>
<div>글내용: {{post.content_html | safe}}</div>

{% for post_image in post.postimage_set.all %}
<img src="{{post_image.image.url}}" style="max-width:200px;">
{% endfor %}

<!--
    이 post가 가진 PostImage들을 출력
    <img src="무언가.image.url">
-->
<!--
    post_list에 POST 요청을 보내는 Form 구현
    - input을 갖지 않음
    - csrf_token만 추가
    - 보내는 곳(action)에, {#{% url %}#} 태그를 적절히 활용
      Post의 pk에 따라 위와 같은 URL을 동적으로 생성해야 함
-->
<form action="{% url 'posts:post-like' pk=post.pk %}" method="POST">
    {% csrf_token %}

    <!--
        사용 가능한 변수는 user(USER), post(POST)
        좋아요 눌린 상태 : PostLike 객체가 존재하는 상태
                    PostLike.objects.filter(user=user,post=post).exist()

        user와 post.like_users를 적절히 이용해서
        현재 request.user가 이 Post의 like_users에 포함되는지를 검사해서
        아래의 if/else/endif 구문이 동작하도록 작성해본다.

        Template에서의 메서드 콜
            post.like_users.all() -> post.like_users.all
            호출구문을 제외해야한다.

        in operator
        <변수> in <반복가능개체(QuerySet 등)>
        -> True, False를 반환
    -->

    {% if user in post.like_users.all %}
    {# {% if post in user.like_post_set.all %} #}
    <button class="btn btn-primary" type="submit">좋아요 취소</button>
    {% else %}
    <button class="btn btn-outline-primary" type="submit">좋아요</button>
    {% endif %}
</form>

<div>
    {% for comment in post.postcomment_set.all %}
    <ul>
        <li>
            <b>작성자: {{comment.author}}</b>
            <span>내용: {{comment.content}}</span>
        </li>
    </ul>
    {% endfor %}
</div>

<form action="{% url 'posts:comment-create' post_pk=post.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <button type="submit">OK</button>
</form>

<hr>
{% endfor %}
{% endblock %}