app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from members.views import signup_view
from posts.views import post_list

urlpatterns_apis = [
    path('members/', include('members.urls.apis')),
    path('posts/', include('posts.urls.apis')),
]

urlpatterns = [
    path('api/', include(urlpatterns_apis)),

    path('', signup_view, name='signup'),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls.views')),
    path('posts/', include('posts.urls.views')),

    path('explore/tags/<str:tag>/', post_list, name='post-list-by-tag'),
]

urlpatterns += static(
    # prefix='/media/',
    # URL 앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root위체어서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/posts/urls.py
from django.urls import path

from . import views
from .views import post_create, comment_create

app_name = 'posts'

urlpatterns = [
    # /posts/
    path('', views.post_list, name='post-list'),
    # path('explore/tags/<str:tag>/', post_list_by_tag, name='post-list-by-tag'),

    # /posts/3/like/
    path('<int:pk>/like/', views.post_like, name='post-like'),

    path('create/', post_create, name="post-create"),
    path('<int:post_pk>/comments/create/', comment_create, name="comment-create"),
]

app/members/urls/views.py
from django.urls import path

from .. import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('naver-login/', views.naver_login, name='naver-login'),
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css'%}">
    <title>Instagram2</title>
    {% block head %}{% endblock %}
</head>
<body>
    <div id="wrap">
    {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="mr-auto ml-auto mt-3 col-lg-4 col-md-6 col-sm-8 col-10">
            <div class="card text-center p-4">
                <h1>Instagram</h1>
                <p class="text-secondary">친구들의 사진과 동영상을 보려면 가입하세요</p>
                <button type="button" class="btn btn-primary btn-md">Facebook으로 로그인</button>
                <div class="dropdown-divider mt-4"></div>

                <form action="" method="POST">
                    {% csrf_token %}
                    <div>{{request.user}}</div>
                    <div>{{request.user.is_authenticated}}</div>
                    <input type="email" name="email" class="form-control mt-3" placeholder="이메일 주소">
                    <input type="text" name="username" class="form-control mt-3" placeholder="성명">
                    <input type="text" name="name" class="form-control mt-3" placeholder="사용자 이름">
                    <input type="password" name="password" class="form-control mt-3" placeholder="비밀번호">
                    <button type="submit" class="btn btn-primary btn-md mt-3 btn-block">가입</button>
                </form>
                <p class="mt-3 text-secondary">가입하면 Instagram의 약관, 데이터 정책 및 쿠키 정책에 동의하게 됩니다. </p>
            </div>

            <div class="card text-center mt-3 mb-3 pt-3 pb-3">
                <div class="card-body">
                    계정이 있으신가요? <a href="{% url 'members:login' %}">로그인</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}